### ISSUE TITLE
Refresh from template

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ember-repo-template#11]
This was delivered, then `ember-template` was updated. I normally don't like these "refresh from template" issues 'cause they should happen anyway, but this is more important because this lesson will be AT LEAST one template behind by the time 015 delivers this material.

**Comment by raq929** [comment]
Is this issue supposed to be on `ember-template`, or on another repo?

**Comment by payne-chris-r** [comment]
Definitely some other repo... I might be able to figure out by date but since it's "update from template" I'm just going to close.
